name: Client Side Tools and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process clang-tidy warnings
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: clang-fixes.yaml

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install openjdk-8-jdk openjdk-8-jre
          pip3 install coverage
          pip3 install pytest

      - name: Run tests and collect coverage
        run: |
          gcc -o my_program *.c -fprofile-arcs -ftest-coverage
          ./my_program
          gcov *.c

      - name: Generate coverage XML report
        run: |
          sudo apt-get install lcov
          pip install lcov-to-cobertura-xml
          lcov --capture --directory . --output-file coverage.info
          lcov --list coverage.info # Optional, for human-readable summary
          lcov_cobertura coverage.info --output $GITHUB_WORKSPACE/coverage.xml

      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $GITHUB_WORKSPACE/coverage.xml

      - name: Setup Codacy Clang-Tidy
        run: |
          curl -sSL https://github.com/codacy/codacy-clang-tidy/releases/download/${{ env.CODACY_CLANG_TIDY_VERSION }}/codacy-clang-tidy-${{ env.CODACY_CLANG_TIDY_VERSION }}.tar.gz | tar xz

      - name: Run Codacy Clang-Tidy Analysis
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          COMMIT: ${{ github.sha }}
          CODACY_URL: ${{ secrets.CODACY_URL }} # Optional: Define if you're using a self-hosted version of Codacy
          CODACY_CLANG_TIDY_VERSION: "0.2.3"
        run: |
          export CODACY_CLANG_TIDY_PATH="./codacy-clang-tidy-${CODACY_CLANG_TIDY_VERSION}"
          clang-tidy <clang-tidy-configs> | \
          $CODACY_CLANG_TIDY_PATH/scripts/send-results.sh
