name: Client Side Tools and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process clang-tidy warnings
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: clang-fixes.yaml

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install openjdk-8-jdk openjdk-8-jre bear
          pip3 install coverage
          pip3 install pytest

      - name: Run tests and collect coverage
        run: |
          gcc -o my_program *.c -fprofile-arcs -ftest-coverage
          ./my_program
          gcov *.c

      - name: Generate coverage XML report
        run: |
          sudo apt-get update -y
          sudo apt-get install lcov -y
          pip3 install lcov_cobertura
          lcov --capture --directory . --output-file coverage.info
          lcov --list coverage.info # Optional, for human-readable summary
          lcov_cobertura coverage.info --output $GITHUB_WORKSPACE/coverage.xml

      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $GITHUB_WORKSPACE/coverage.xml

      - name: Setup Codacy Clang-Tidy
        run: |
          curl -sSL https://github.com/codacy/codacy-clang-tidy/archive/refs/tags/1.3.8.tar.gz | tar xz

      - name: Generate Compilation Database
        run: |
          bear -- gcc -o my_program *.c -fprofile-arcs -ftest-coverage

      - name: Run Codacy Clang-Tidy Analysis
        env:
          PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          COMMIT: ${{ github.sha }}
          CODACY_CLANG_TIDY_VERSION: "1.3.8"
        run: |
          export CODACY_CLANG_TIDY_PATH="./codacy-clang-tidy-1.3.8"
          cd +x $CODACY_CLANG_TIDY_PATH/scripts/
          chmod +x send-results.sh
          clang-tidy -checks=* -p=. *.c | \
          ./send-results.sh
